// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int VisualUser_3d8e0d6bf6d1f18448fd5924dc4297a2Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "VisualUser_3d8e0d6bf6d1f18448fd5924dc4297a2", 0 },

		};
	}
}
