// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_550bb64c_41b0_4d54_b764_3fcaa77cf507 : ReferenceBinding
	{
		private VisualUser CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (VisualUser)UnityComponent;
		}
		public override string CoherenceComponentName => "VisualUser_VisualUser_2895662808262937726";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.controllerLeft);
			set => CastedUnityComponent.controllerLeft = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			return update.controllerLeft;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			update.controllerLeft = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new VisualUser_VisualUser_2895662808262937726();
		}
	}

	public class Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_caac249c_f5a5_437b_900d_65773bc87f64 : ReferenceBinding
	{
		private VisualUser CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (VisualUser)UnityComponent;
		}
		public override string CoherenceComponentName => "VisualUser_VisualUser_2895662808262937726";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.controllerRight);
			set => CastedUnityComponent.controllerRight = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			return update.controllerRight;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			update.controllerRight = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new VisualUser_VisualUser_2895662808262937726();
		}
	}

	public class Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_b900ef6f_1feb_4d79_b345_35b6d74e7aab : ReferenceBinding
	{
		private VisualUser CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (VisualUser)UnityComponent;
		}
		public override string CoherenceComponentName => "VisualUser_VisualUser_2895662808262937726";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.targetHead);
			set => CastedUnityComponent.targetHead = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			return update.targetHead;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			update.targetHead = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new VisualUser_VisualUser_2895662808262937726();
		}
	}

	public class Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_0adf2717_64ba_4a79_9ef9_d192c14fcf83 : BoolBinding
	{
		private VisualUser CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (VisualUser)UnityComponent;
		}
		public override string CoherenceComponentName => "VisualUser_VisualUser_2895662808262937726";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.controllerLeftEnable);
			set => CastedUnityComponent.controllerLeftEnable = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			return update.controllerLeftEnable;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			update.controllerLeftEnable = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new VisualUser_VisualUser_2895662808262937726();
		}
	}

	public class Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_2edcbe1f_1b84_4bcd_8584_7a1d2a3e3d69 : BoolBinding
	{
		private VisualUser CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (VisualUser)UnityComponent;
		}
		public override string CoherenceComponentName => "VisualUser_VisualUser_2895662808262937726";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.controllerRightEnable);
			set => CastedUnityComponent.controllerRightEnable = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			return update.controllerRightEnable;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (VisualUser_VisualUser_2895662808262937726)coherenceComponent;
			update.controllerRightEnable = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new VisualUser_VisualUser_2895662808262937726();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'VisualUser' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncVisualUser : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncVisualUser>();
			if (coherenceSync.TryGetBindingByGuid("550bb64c-41b0-4d54-b764-3fcaa77cf507", "controllerLeft", out Binding InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeft))
			{
				var clone = new Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_550bb64c_41b0_4d54_b764_3fcaa77cf507();
				InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeft.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeft)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (VisualUser).controllerLeft");
			}
			if (coherenceSync.TryGetBindingByGuid("caac249c-f5a5-437b-900d-65773bc87f64", "controllerRight", out Binding InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRight))
			{
				var clone = new Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_caac249c_f5a5_437b_900d_65773bc87f64();
				InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRight.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRight)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (VisualUser).controllerRight");
			}
			if (coherenceSync.TryGetBindingByGuid("b900ef6f-1feb-4d79-b345-35b6d74e7aab", "targetHead", out Binding InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_targetHead))
			{
				var clone = new Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_b900ef6f_1feb_4d79_b345_35b6d74e7aab();
				InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_targetHead.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_targetHead)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (VisualUser).targetHead");
			}
			if (coherenceSync.TryGetBindingByGuid("0adf2717-64ba-4a79-9ef9-d192c14fcf83", "controllerLeftEnable", out Binding InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeftEnable))
			{
				var clone = new Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_0adf2717_64ba_4a79_9ef9_d192c14fcf83();
				InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeftEnable.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerLeftEnable)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (VisualUser).controllerLeftEnable");
			}
			if (coherenceSync.TryGetBindingByGuid("2edcbe1f-1b84-4bcd-8584-7a1d2a3e3d69", "controllerRightEnable", out Binding InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRightEnable))
			{
				var clone = new Binding_3d8e0d6bf6d1f18448fd5924dc4297a2_2edcbe1f_1b84_4bcd_8584_7a1d2a3e3d69();
				InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRightEnable.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalVisualUser_VisualUser_2895662808262937726_VisualUser_VisualUser_2895662808262937726_controllerRightEnable)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (VisualUser).controllerRightEnable");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncVisualUser] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
